### ISSUE TITLE
3dsmax 2015 trying export getting error message

### ISSUE THREAD

**Issue by AW-84** [steptosky/XplnObj#1]
Hi 

I keep getting the following message "there are no x-obj found", followed by the below.
- - - -   File to process: E:\X plane Custom AW Objects\export\Gelenddzhik\Gelendzhik V 1.obj
- - - -   File to process: E:\X plane Custom AW Objects\export\Gelenddzhik\Gelendzhik V 1.obj
- - - -   SelectedOnly: false
- - - -   SelectedOnly: false
- - - -   Current time: 0
- - - -   Current time: 0
ERR: There are no X-Obj object found.
ERR: There are no X-Obj object found.
- - - -   Found 0 main object. Selected 0
- - - -   Found 0 main object. Selected 0
- - - -   Export completed with:
	2 errors 
	0 warnings
- - - -   Export completed with:
	2 errors 
	0 warnings
ERR: Error during check update the plugin. The log contains more information. Please, inform the developers.
ERR: Error during check update the plugin. The log contains more information. Please, inform the developers.

I tried the below, but I couldn't find the DLU files that were mentioned.
"I had trouble getting this plugin running, and placed the two DLL files in the root directory of 3dsMax. I failed to notice there was a C:\Plugins\SteptoSky folder containing a .DLU and help files. That needs to be copied over to the Max root to get it started.  "

Any advice?

**Comment by Pancir** [comment]
Hello sorry for delay, It seems my notifications setup is not correct.
The correct repository for the plugin here https://github.com/steptosky/3DsMax-XplnObj/issues this repository is for library.

Only one version of the plugin can be installed at the same time. 
The new version and documentation have been released
Plugin https://github.com/steptosky/3DsMax-XplnObj/releases
Doc https://github.com/steptosky/3DsMax-XplnObj-Doc/releases
The documentation should help you to solve the problem with "There are no X-Obj object found"
Also I see the problem with the auto-update checking, could you please attach the log file?

**Comment by AW-84** [comment]
Hi Pancir,

Sorry for my late reply, thank you for the email. I appreciate the reply, any answer is better than no answer.

I've been able to export the model and get it into WED and I can view it using an object view app.
However the model is grey. The texture don't seem to be getting exported.
I've created a thread on the X plane Org. I'll include the link as I attached a file with the 3dsmax 2015 saved file and the Photoshop file.
I'm hoping someone will look it over and go "oh it's this" :)

http://forums.x-plane.org/index.php?/forums/topic/125857-exported-3ds-max-model-is-grey-help/

Anyway again thank you for your assistance.

Best regards Andy
On 10/07/2017 15:28:53, Pancir <notifications@github.com> wrote:
Hello sorry for delay, It seems my notifications setup is not correct.
The correct repository for the plugin here https://github.com/steptosky/3DsMax-XplnObj/issues [https://github.com/steptosky/3DsMax-XplnObj/issues] this repository is for library.
Only one version of the plugin can be installed at the same time.
The new version and documentation have been released
Plugin https://github.com/steptosky/3DsMax-XplnObj/releases [https://github.com/steptosky/3DsMax-XplnObj/releases]
Doc https://github.com/steptosky/3DsMax-XplnObj-Doc/releases [https://github.com/steptosky/3DsMax-XplnObj-Doc/releases]
The documentation should help you to solve the problem with "There are no X-Obj object found"
Also I see the problem with the auto-update checking, could you please attach the log file?

**Comment by Pancir** [comment]
Have you put your textures near your objects in the aircraft folder? 
When you specify a texture for an object in the plugin it just takes the texture name and write it into obj file. It does not do something else with the texture, so in the aircraft folder you have to put a texture with the correct name which is written inside obj file.
I will write this information in the next help version.

**Comment by AW-84** [comment]
Yes the texture are in the same folder as the obj file.
I put the folder in the custom scenery folder and the aircraft folder.

I tried using PNG and DDS format.

I've tried loading the textures from different locations. Xplane folder, the 3dsmax project folder

I've included the error log in case that help?

I'm wandering if I haven't loaded a necessary dependencies.
Do I just need the 3DsMax2015-XplnObj-x64?


I've include the error log and the obj file. Hopefully it will help.

Best regards AW
On 15/07/2017 06:08:37, Pancir <notifications@github.com> wrote:
Have you put your textures near your objects in the aircraft folder?
When you specify a texture for an object in the plugin it just takes the texture name and write it into obj file. It does not do something else with the texture, so in the aircraft folder you have to put a texture with the correct name which is written inside obj file.
I will write this information in the next help version.

**Comment by Pancir** [comment]
> Do I just need the 3DsMax2015-XplnObj-x64?

Yes, there are no any additional dependencies.

> I've include the error log and the obj file. Hopefully it will help.

I guess github has filtered this data because I don't see anything attached, use github form.
https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

Anyway if you see the correct texture name inside your obj file then probably the plugin works correctly and the problem somewhere else. The texture path in an obj file is relative from this obj, make sure it is true for your situation.

**Comment by AW-84** [comment]
Success!!

Figure out where I was going wrong. The texture names had spaces.
Texture names were "Main Terminal Complete" , needs to be "MainTerminalComplete" 

Such a simple thing. Well its working :)

Thanks for your help, and thanks for the exporter.
Best Regards AW
On 15/07/2017 15:15:45, Pancir <notifications@github.com> wrote:
Do I just need the 3DsMax2015-XplnObj-x64?
Yes, there are no any additional dependencies.
I've include the error log and the obj file. Hopefully it will help.
I guess github has filtered this data because I don't see anything attached, use github form.
https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/ [https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/]
Anyway if you see the correct texture name inside your obj file then probably the plugin works correctly and the problem somewhere else. The texture path in an obj file is relative from this obj, make sure it is true for your situation.

**Comment by Pancir** [comment]
I have added checking for such a situation. In on of the next version it will be available and error will be printed if you have illegal symbols in the textures names.
